[package]
name = "nvimapisys"
version = "0.1.0"
edition = "2024"

[dependencies]
rmpv.workspace = true
log.workspace = true
env_logger.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json = "1.0"
tokio = {workspace = true, features = ["sync"]}

[lints]
workspace = true
